"""``config init`` / ``config show`` subcommands."""

from __future__ import annotations

from pathlib import Path

import click
import yaml as _yaml

from scholium.config import Config

from ._terminal import _OK


_CONFIG_TEMPLATE = """\
# Scholium configuration file
# Generated by: scholium config init
#
# This file is optional — Scholium uses built-in defaults for every setting.
# Only include the keys you want to override.
#
# Tip: keep this file alongside your lecture .md files so each project
# can have its own slide backend, TTS provider, voice, and timing settings.

# ── Slide backend ────────────────────────────────────────────────────────────
# Which engine renders your markdown into slide PNGs.
#   pandoc  — Pandoc + Beamer → PDF → PNG (requires pandoc + LaTeX)
#   slidev  — Slidev (Vue) → headless Chromium → PNG (requires Node.js)
#   marp    — Marp CLI (Puppeteer) → Chromium → PNG (requires Node.js)
#
# Per-lecture overrides: add `slide-backend: marp` (hyphenated, Pandoc-style)
# alongside `slide-level:` in a lecture's own YAML frontmatter.  CLI flag
# `--slide-backend` overrides everything.  Run `scholium slides list`
# to probe each backend's external dependencies.
slide_backend: "pandoc"

# Each backend has its own section below.  All three accept a
# `frontmatter:` overlay merged into every generated deck — useful for
# title-slide metadata, language tags, etc.  Three keys are portable
# (same name, same values, work across all three backends):
#
#   title:  string                      → Pandoc deck title, Slidev/Marp metadata
#   author: string                      → Pandoc deck author, Slidev/Marp metadata
#   lang:   IETF tag (e.g. "en", "de")  → document language
#
# Any other key is backend-specific — see each backend's own docs for
# the full surface (Pandoc YAML variables, Slidev headmatter, Marp/
# Marpit directives).

# ── Pandoc backend settings ──────────────────────────────────────────────────
# Only honoured when slide_backend == pandoc.  Merged into the source's
# YAML metadata via `--metadata-file`; values here override anything of
# the same name written in the source .md frontmatter.
pandoc:
  # template: "beamer"     # Pandoc output format (default: beamer)
  # dpi: 300               # PNG rasterisation DPI (default: 300)
  # frontmatter:           # extra YAML metadata, e.g.
  #   aspectratio: 169     #   Beamer 16:9 deck
  #   theme: "metropolis"  #   Beamer theme
  #   lang: "en-AU"
  #   header-includes: |
  #     \\usepackage{siunitx}
  frontmatter: {}

# (Legacy key, still honoured if you have an older config:)
# pandoc_template: "beamer"

# ── Slidev backend settings ──────────────────────────────────────────────────
# Only honoured when slide_backend == slidev.
# Install: npm install -g @slidev/cli playwright-chromium && npx playwright install chromium
slidev:
  theme: "default"                 # "default" → Slidev's built-in styling (no
                                   # separate theme package needed); use a name
                                   # like "@slidev/theme-seriph" for others.
  command: ["npx", "@slidev/cli"]  # how to invoke the Slidev CLI
  timeout: 600                     # seconds for PNG export to complete
  with_clicks: false               # export each click step as a separate PNG
  # extra_args: ["--dark"]         # forwarded verbatim to `slidev export`
  # frontmatter:                   # merged into every generated deck, e.g.
  #   colorSchema: "dark"          #   Slidev: "auto" | "light" | "dark"
  #   htmlAttrs: { lang: "en-AU" } #   IETF lang tag (Slidev nests it)
  frontmatter: {}

# ── Marp backend settings ────────────────────────────────────────────────────
# Only honoured when slide_backend == marp.
# Install: npm install -g @marp-team/marp-cli  (themes ship inside the CLI).
# Marp drives Chromium via Puppeteer; on hardened Linux it needs --no-sandbox,
# which is added automatically when no_sandbox: true (default).
marp:
  theme: "default"                          # default | gaia | uncover (built-in)
  command: ["npx", "@marp-team/marp-cli"]   # how to invoke the Marp CLI
  paginate: false                           # show slide numbers
  no_sandbox: true                          # add --no-sandbox via CHROME_NO_SANDBOX
  # browser: "chrome"                       # chrome | edge | firefox | auto
  # browser_path: "/path/to/chrome"         # explicit Chromium binary (recommended)
  # extra_args: ["--allow-local-files"]     # forwarded verbatim to `marp`
  # frontmatter:                            # merged into every generated deck, e.g.
  #   lang: "en-AU"                         #   Marpit honours `lang:`
  #   header: "Lecture 3"                   #   Marp: text shown on every slide
  #   footer: "Physics 101"
  frontmatter: {}

# ── TTS provider ─────────────────────────────────────────────────────────────
# Which TTS engine to use.  Run `scholium voice list` to see what is
# installed.  Choices: piper, elevenlabs, openai, coqui, bark, f5tts,
# styletts2, tortoise
tts_provider: "piper"

# Default voice (meaning depends on provider):
#   piper      — voice model name, e.g. en_US-lessac-medium
#   elevenlabs — ElevenLabs voice ID (run `scholium list-voices --provider elevenlabs`)
#   openai     — alloy | echo | fable | onyx | nova | shimmer
#   coqui/f5tts/styletts2/tortoise — name from `scholium list-voices`
voice: "en_US-lessac-medium"

# ── Piper settings ────────────────────────────────────────────────────────────
piper:
  quality: "medium"   # low | medium | high  (selects voice model variant)
  speed: 1.0          # speech rate  0.1–5.0  (1.0 = normal; 0.8 = 20% slower)

# ── ElevenLabs settings ───────────────────────────────────────────────────────
elevenlabs:
  model: "eleven_multilingual_v2"
  # stability: 0.5        # 0.0–1.0  higher = more consistent, lower = more expressive
  # similarity_boost: 0.75  # 0.0–1.0  how closely to match the reference voice

# ── OpenAI TTS settings ───────────────────────────────────────────────────────
openai:
  model: "tts-1"    # tts-1 | tts-1-hd (higher quality, higher cost)
  speed: 1.0        # speech rate  0.25–4.0  (1.0 = normal)

# ── Coqui TTS settings ────────────────────────────────────────────────────────
coqui:
  model: "tts_models/multilingual/multi-dataset/xtts_v2"

# ── Bark settings ─────────────────────────────────────────────────────────────
bark:
  model: "small"   # small | large  (large is higher quality but much slower)

# ── F5-TTS settings ───────────────────────────────────────────────────────────
f5tts:
  model: "F5-TTS"   # F5-TTS | E2-TTS
  vocoder: "vocos"  # vocos | bigvgan
  # model_path: "my_voice/sample.wav"  # ref audio; relative to voices_dir or absolute
  # ref_text: "The text spoken in the reference clip."

# ── StyleTTS2 settings ────────────────────────────────────────────────────────
styletts2:
  alpha: 0.3           # 0.0–1.0  style blend  (0 = reference style, 1 = model default)
  beta: 0.7            # 0.0–1.0  diffusion guidance strength
  diffusion_steps: 5   # 1–20  more steps = slower but higher quality
  # model_path: "my_voice/sample.wav"

# ── Tortoise TTS settings ─────────────────────────────────────────────────────
tortoise:
  preset: "fast"   # ultra_fast | fast | standard | high_quality
  kv_cache: true
  half: true       # use float16 — faster on GPU, slight quality reduction
  # model_path: "my_voice/sample.wav"

# ── Video settings ────────────────────────────────────────────────────────────
# resolution and fps drive both slide rasterisation (slide backends) and the
# final mp4 encode (ffmpeg); they share a single source of truth here.
resolution: [1920, 1080]   # output resolution [width, height]
fps: 30

# ── Video encoding (ffmpeg) ──────────────────────────────────────────────────
# Run `scholium video list` to see which codecs and hwaccels are compiled
# into your ffmpeg.  Switch to `h264_nvenc` (or `hevc_nvenc`) for 5-10×
# faster encodes on an NVIDIA GPU, or `libvpx-vp9` / `libaom-av1` for
# smaller files at the cost of CPU time.
video:
  codec: "libx264"          # libx264 | libx265 | libvpx-vp9 | libaom-av1 | h264_nvenc | ...
  preset: "medium"          # ultrafast … veryslow  (x264/x265 only; ignored otherwise)
  crf: 23                   # 0=lossless, 18=visually-lossless, 23=default
  pixel_format: "yuv420p"   # yuv420p = broadest compatibility
  audio_codec: "aac"        # aac | libopus | libmp3lame | flac | ...
  audio_bitrate: "192k"
  extra_args: []            # forwarded verbatim to every ffmpeg call

# ── Timing defaults ───────────────────────────────────────────────────────────
timing:
  default_pre_delay: 1.0    # seconds of silence before narration
  default_post_delay: 2.0   # seconds of silence after narration
  min_slide_duration: 4.0   # minimum slide duration in seconds
  silent_slide_duration: 3.0  # duration for slides with no narration (TOC etc.)

# ── File paths ────────────────────────────────────────────────────────────────
voices_dir: "~/.local/share/scholium/voices"
temp_dir: "./temp"
audio_cache:
  enabled: true
  dir: "~/.cache/scholium/audio"
output_dir: "./output"
keep_temp_files: false   # set true to inspect intermediate files when debugging
"""


@click.group("config")
def config() -> None:
    """Manage Scholium configuration."""


@config.command("init")
@click.option(
    "--path",
    default="config.yaml",
    show_default=True,
    help="Path for the new config file.",
)
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite an existing file.",
)
def config_init(path: str, force: bool) -> None:
    """Create a config.yaml with all settings and inline documentation.

    The generated file contains every supported option with its default value
    and an explanatory comment.  Edit it to override only the settings you
    need — all others fall back to the built-in defaults.

    Examples:
        scholium config init
        scholium config init --path my_project/config.yaml
        scholium config init --force    # overwrite existing file
    """
    dest = Path(path)
    if dest.exists() and not force:
        raise click.ClickException(f"'{path}' already exists.  Use --force to overwrite.")

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(_CONFIG_TEMPLATE)
    click.echo(f"{_OK} Created: {dest}")
    click.echo("\nEdit the file to override only the settings you need.")
    click.echo("Run `scholium config show` at any time to see the effective configuration.")


@config.command("show")
@click.option(
    "--path",
    "config_path",
    default="config.yaml",
    show_default=True,
    help="Path to config file.",
)
def config_show(config_path: str) -> None:
    """Show the current effective configuration.

    Merges built-in defaults with your config.yaml and environment variables,
    then prints the result.  API keys are masked.

    Examples:
        scholium config show
        scholium config show --path my_project/config.yaml
    """
    cfg = Config(config_path)
    data = cfg.config

    _mask_secrets(data)

    click.echo(_yaml.dump(data, default_flow_style=False, sort_keys=False), nl=False)


# Keys whose suffix marks them as a secret that ``config show`` should
# mask before printing.  Lowercase substring match against the key name.
_SECRET_KEY_SUFFIXES = ("api_key", "token", "secret", "password")
_MASK = "***"


def _mask_secrets(node) -> None:
    """Recursively replace secret-looking string values with ``_MASK`` in place.

    Walks every dict reachable from ``node`` and rewrites any key whose
    name ends in one of :data:`_SECRET_KEY_SUFFIXES` (case-insensitive).
    Lists are traversed so embedded dicts get masked too.  Non-string
    values, empty strings, and ``None`` are left alone — only set
    values get masked, so users can still see at a glance whether a
    secret is configured.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(key, str) and any(
                key.lower().endswith(suffix) for suffix in _SECRET_KEY_SUFFIXES
            ):
                if isinstance(value, str) and value:
                    node[key] = _MASK
            else:
                _mask_secrets(value)
    elif isinstance(node, list):
        for item in node:
            _mask_secrets(item)


__all__ = ["config", "config_init", "config_show", "_CONFIG_TEMPLATE"]
